# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  # env:
 
  #   runs-on: ubuntu-18.04
 
  #   steps:
  #   - name: Make envfile
  #     uses: SpicyPizza/create-envfile@v1
  #     with:
  #       PORT: 2001
  #       NODE_ENV: development
  #       PGUSER: root
  #       PGDATABASE: clean_api
  #       PGPASSWORD: secret
  #       PGPORT: 5432
  #       PGHOST: postgres
  #       ALGORITHM: aes-256-gcm
  #       ENCRYPTION_KEY: 3zTvzr3p67VC61jmV54rIYu1545x4TlY
  #       IV: 60iP0h6vJoEa
  #       name: rod
  #       pass: qwerty

  build:
    runs-on: ubuntu-latest
    # needs: env # need env file to run test
    env:
      PORT: 2001
      NODE_ENV: development
      PGUSER: root
      PGDATABASE: clean_api
      PGDATABASE_TEST: clean_api
      PGPASSWORD: secret
      PGPORT: 5432
      PGHOST: localhost
      ALGORITHM: aes-256-gcm
      ENCRYPTION_KEY: 3zTvzr3p67VC61jmV54rIYu1545x4TlY
      IV: 60iP0h6vJoEa
      name: rod
      pass: qwerty
      BASE_URL: http://localhost
      TEST_PORT: 2001
      CI: true
    strategy:
      matrix:
        node-version: [14.17.3]
    # pg db
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: clean_api
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npx sequelize-cli db:migrate
    - run: npm run utest
    - run: npm start
    - run: npm run itest